version: "3"
services:
  mongodb:
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "18642:18642"
    environment:
      MONGO_INITDB_DATABASE: hospital
  microservice:
    restart: always
    build:
      context: project-microservices/ms1-test/.
      dockerfile: Dockerfile
    ports:
      - "4010:4010"
    environment:
      MongoURL: mongodb://host.docker.internal:18642/
  appapi:
    build:
      context: project-api/.
      dockerfile: Dockerfile
    ports:
      - "8080:3010"
    links:
      - microservice
    environment:
      MicroServiceBaseURL: "http://microservice:4010/api/"
